package main

import (
	"io"
	"io/ioutil"
	"log"
	"os"
	"strings"
)

/**
 *  Reads all txt files in the dictionary directory
 *  and encodes them as strings literals in textfiles.go
 */
func main() {
	dirname := "./vocabulary/"
	fs, _ := ioutil.ReadDir(dirname)
	out, _ := os.Create("vocabulary.go")
	out.Write([]byte("// THIS CODE WAS GENERATED BY: embedVocab.go\npackage main\n\n"))
	out.Write([]byte("// Vocabulary : all text files found in the vocabulary\n"))
	out.Write([]byte("// directory are embedded in this slice as strings\n"))
	out.Write([]byte("var Vocabulary = []string{\n"))
	for _, f := range fs {
		if strings.HasSuffix(f.Name(), ".txt") {
			out.Write([]byte("`"))
			if f, err := os.Open(dirname + f.Name()); err != nil {
				log.Fatal(err)

			} else {
				io.Copy(out, f)
				out.Write([]byte("`,\n\n"))
			}
		}
	}
	out.Write([]byte("}\n"))
}
